version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb+srv://admin:admin@cluster0.te756.mongodb.net/chat-app?retryWrites=true&w=majority
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"